theme = "terminimal"
base_url = "https://shawn111.github.io/"


# Sass compilation is required
compile_sass = true

[extra]

# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
author = "Shawn Wang"
